name: Deploy stack in two regions

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  REGION: 'us-east-1'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository onto the GitHub actions runner (needed so the action can see our files)
      - name: Checkout repository
        uses: actions/checkout@master

      # Authenticate with AWS using the IAM Role stored in the Github repository's secrets.
      # Note: Secret values can be configured in the settings tab on a GitHub repository.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ env.REGION }}

      - name: Deploy stack
        run: |
          sam deploy

